language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"

before_script:
  - wget https://github.com/mybb/mybb/archive/mybb_1615.zip
  - unzip mybb_1615.zip
  - cp -r ./mybb-mybb_1615/* ./src
  - rm -r mybb-mybb_1615